version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: net.sourceforge.pmd:pmd-core
    versions:
    - ">= 6.18.a"
    - "< 6.19"
  - dependency-name: net.sourceforge.pmd:pmd-java
    versions:
    - ">= 6.18.a"
    - "< 6.19"
  - dependency-name: org.eclipse.collections:eclipse-collections
    versions:
    - ">= 10.a"
    - "< 11"
  - dependency-name: org.eclipse.collections:eclipse-collections-api
    versions:
    - ">= 10.a"
    - "< 11"
  - dependency-name: org.jenkins-ci.plugins:junit
    versions:
    - "> 1.3"
  - dependency-name: org.jenkins-ci.plugins:script-security
    versions:
    - "> 1.62"
  - dependency-name: org.jenkins-ci.plugins.workflow:workflow-step-api
    versions:
    - "> 2.20"
